language: node_js

sudo: required

services:
  - docker

node_js:
  - "12"

arch:
  - amd64

os: 
  - linux

install:
  - npm install
  - cd ./utils
  - sh ./build.sh
  - cd ..

script:
  - cd ./utils/opencv/build_wasm/bin
  - node tests.js
  - cd ../../../../
  - npm test
